version: 2.1

jobs:
  build:
    working_directory: /Vision
    docker:
      - image: "arminpcm/vision:latest"
    steps:
      - checkout
      - run:
          name: Build with Bazel
          command: |
            docker build -t arminpcm/vision:latest -f Container/Dev.dockerfile .
            docker run arminpcm/vision:latest bazel build //...
  test:
    working_directory: /Vision
    docker:
      - image: "arminpcm/vision:latest"
    steps:
      - checkout
      - run: docker run arminpcm/vision:latest bazel test //...

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
