version: 2.1

jobs:
  build:
    working_directory: /Vision
    docker:
      - image: "arminpcm/vision:latest"
    steps:
      - checkout
      - run:
          name: Build with Bazel
          command: |
            bazel build //...
  test:
    working_directory: /Vision
    docker:
      - image: "arminpcm/vision:latest"
    steps:
      - checkout
      - run: bazel test //...

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
