version: 2.1

jobs:
  build:
    working_directory: /Vision
    docker:
      - image: "arminpcm/vision:latest"
    steps:
      - checkout
      - run:
          name: Build and test with Bazel
          command: |
            bazel build //... --config clang-tidy
            bazel test //...

workflows:
  build_and_test:
    jobs:
      - build
